---
title: "R Notebook"
output: html_notebook
---



```{r}
#read document
library(tidyverse)

df = read_csv("/Users/tinganlai/Documents/GitHub/PraticumProject-/Consumer_Complaints_lemma.csv")



df1 = df['Complaint_clean'][1:10000,]
head(df1)
df1 = cbind(df1, df['Product'][1:10000,])
head(df1)
train_posts <- df1['Complaint_clean'][1:8000,]
train_tags <- df1['Product'][1:8000,]

test_posts <- df1['Complaint_clean'][8001:10000,]
test_tags <- df1['Product'][8001:10000,]



```


```{r}
library(keras)
library(tidyverse)
tokenizer <- text_tokenizer(num_words = 500) %>%
  fit_text_tokenizer(train_posts)
```



```{r}
x_train <- texts_to_matrix(tokenizer, train_posts, mode='tfidf')
  
x_test <- texts_to_matrix(tokenizer, test_posts, mode='tfidf')

#save text tokenizer
save_text_tokenizer(tokenizer, file ='tokenizer')

```

```{r}
oneHot <- function(x) {
  xf <- factor(x)
  return(model.matrix(~xf+0))
  
}


y_train <- oneHot(train_tags)
y_test<- oneHot(test_tags)


colnames(y_train)
text_labels <-  levels(as.factor(train_tags))
text_labels

saveRDS (text_labels, file='text_labels.rds')


```




```{r}

#Building model
model  <- keras_model_sequential() %>%
  layer_dense(units=512, activation='relu', input_shape=c(500)) %>%
  layer_dropout(rate=0.5) %>%
  layer_dense(units=length(text_labels), activation='softmax')

model %>% compile(
  optimizer='adam',
  loss = 'categorical_crossentropy',
  metrics=c('accuracy')
)


#fit the model
history <- model %>% fit (
  x_train,
  y_train,
  epochs=10,
  batch_size=300,
  validation_data=list(x_test,y_test)
)
  
results <- model %>% evaluate (x_test,y_test)
results


```



```{r}
# look at the prediction output

test <- model %>% predict(x_test[1:100,])
test
#subset and find out the max value and find out the text label
text_labels[which(test[1,]==max(test[1,]))]


#save the model
save_model_hdf5(model, file="My_model.h5")
```

```{r}
 labels <- c()
        for (i in 1:100){
          labels[i] <- text_labels[which(test[i,]==max(test[i,]))]
        }

```

```{r}
#write testing dataset 
test_posts <- df1['Complaint_clean'][8001:10000,]
test_tags <- df1['Product'][8001:10000,]


df_test <- cbind(test_posts, test_tags)

write.csv(df_test,"/Users/tinganlai/Documents/GitHub/PraticumProject-/rshiny/test_in_R.csv", row.names = FALSE)

```




